# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1080, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.design_buttons = QtWidgets.QFrame(self.centralwidget)
        self.design_buttons.setGeometry(QtCore.QRect(0, 0, 221, 121))
        self.design_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.design_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.design_buttons.setObjectName("design_buttons")
        self.catalog = QtWidgets.QFrame(self.centralwidget)
        self.catalog.setGeometry(QtCore.QRect(0, 120, 221, 311))
        self.catalog.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.catalog.setFrameShadow(QtWidgets.QFrame.Raised)
        self.catalog.setObjectName("catalog")
        self.information = QtWidgets.QFrame(self.centralwidget)
        self.information.setGeometry(QtCore.QRect(0, 430, 221, 211))
        self.information.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.information.setFrameShadow(QtWidgets.QFrame.Raised)
        self.information.setObjectName("information")
        self.canvas = QtWidgets.QFrame(self.centralwidget)
        self.canvas.setGeometry(QtCore.QRect(220, 0, 721, 431))
        self.canvas.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.canvas.setFrameShadow(QtWidgets.QFrame.Raised)
        self.canvas.setObjectName("canvas")
        self.caculate = QtWidgets.QFrame(self.centralwidget)
        self.caculate.setGeometry(QtCore.QRect(219, 429, 411, 211))
        self.caculate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.caculate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.caculate.setObjectName("caculate")
        self.log = QtWidgets.QFrame(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(629, 429, 311, 211))
        self.log.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.log.setFrameShadow(QtWidgets.QFrame.Raised)
        self.log.setObjectName("log")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 942, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
